name: Deploy Spring Boot App

on: 
  push:
    branches:
      - main
      
jobs: 
  build: 
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set upt JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        
    - name: Set up Gradle
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      run: .\gradlew test

    - name: Deploy on Render
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
        -H "Accept: application/json" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -d ""
