name: Deploy Spring Boot App

on: 
  push:
    branches:
      - main
      
jobs: 
  build: 
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set upt JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'
        
    - name: Set up Gradle
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      run: .\gradlew test

    - name: Install Railway CLI
      run: npm install -g railway
      
    - name: Deploy on Railway
      run: |
        railway login --token ${{ secrets.RAILWAY_API_KEY }}
        railway up --project ${{ secrets.RAILWAY_PROJECT_ID }}
